#!/bin/bash
pushd src
VCS_REF=$(git rev-parse HEAD)
SOURCE_TAG=$(git describe --exact-match --tags)
popd
docker build --build-arg VCS_REF=${VCS_REF} \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  -t ${IMAGE_NAME} .
