#!/bin/bash
docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${SOURCE_COMMIT}
pushd src
SOURCE_TAG=$(git describe --exact-match --tags)
popd
docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${SOURCE_TAG}
docker push ${DOCKER_REPO}:${SOURCE_COMMIT}
docker push ${DOCKER_REPO}:${SOURCE_TAG}
